### ISSUE TITLE
不开启PATH_INFO模式会出现Notice级别提示

### ISSUE THREAD

**Issue by AxiosCros** [liqiongfan/cspeed#1]
详细信息：
Notice: Cs\App::run(): Unknow index PATH_INFO in /vagrant/cspeed/public/index.php on line 14

追查后发现，是因为/kernel/mvc/dispatch.c:50 传入默认值PATH_INFO
``` c
char *path_info = cspeed_request_server_str_key_val("PATH_INFO");
```

然后在  /kernel/net/request.c:80 中抛出的“PATH_INFO索引不存在”提示

原因是$_SERVER中没有PATH_INFO的key值，即如果不开启PATH_INFO模式的话就会报这个错误。
建议在Readme里说明一下必须要用path_info模式。

另外，readme里的安装步骤少了一步，在php.ini中添加“extension=cspeed.so;”

**Comment by liqiongfan** [comment]
文档开始处说明了必须设置有PATH-INFO信息，框架才生效
README文档确实应该添加说明，感谢您的BUG提交。
